const courses = [
  {
    id: 1,
    title: "JavaScript Algorithms and Data Structures Masterclass",
    author: "Colt Steele",
    rating: 4.4,
    price: 47.13,
    discountPrice: 10.2,
    img: "assets/1.png",
    about:
      "Ushbu kurs sizga JavaScript Algorithms and Data Structures Masterclass bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "x_dev",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-05-02",
        rating: 5,
      },
      {
        username: "coderQueen",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-02-26",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-21",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-16",
        rating: 4,
      },
      {
        username: "coderUz",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-27",
        rating: 5,
      },
      {
        username: "simpleUser",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-05-15",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-05-13",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-28",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-01",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-15",
        rating: 5,
      },
    ],
  },
  {
    id: 2,
    title: "C++ Data Structures & Algorithms + LEETCODE",
    author: "Scott Barrett",
    rating: 4.7,
    price: 80.06,
    discountPrice: 15.1,
    img: "assets/2.png",
    about:
      "Bu kurs orqali siz C++ Data Structures & Algorithms + LEETCODE bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "jsMaster",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-14",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-05-13",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-08",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-04-20",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-02-20",
        rating: 5,
      },
      {
        username: "simpleUser",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-21",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-05-13",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-06",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-10",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-26",
        rating: 5,
      },
    ],
  },
  {
    id: 3,
    title: "Java Data Structures and Algorithms Masterclass",
    author: "Elshad Karimov",
    rating: 4.8,
    price: 41.05,
    discountPrice: 12.19,
    img: "assets/3.png",
    about:
      "Bu kurs orqali siz Java Data Structures and Algorithms Masterclass bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "javohirx",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-01",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-05-14",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-05-16",
        rating: 4,
      },
      {
        username: "coderUz",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-17",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-19",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-03-13",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-03",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-04",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-06",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-23",
        rating: 5,
      },
    ],
  },
  {
    id: 4,
    title: "The Complete Data Structures and Algorithms Course in Java",
    author: "Elshad Karimov",
    rating: 4.7,
    price: 28.31,
    discountPrice: 15.84,
    img: "assets/4.png",
    about:
      "Ushbu kurs sizga The Complete Data Structures and Algorithms Course in Java bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "design2code",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-05-10",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-16",
        rating: 4,
      },
      {
        username: "coderUz",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-02-20",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-03",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-10",
        rating: 5,
      },
      {
        username: "coderQueen",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-15",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-03-27",
        rating: 4,
      },
      {
        username: "jamshid.dev",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-06",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-05-13",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-20",
        rating: 5,
      },
    ],
  },
  {
    id: 5,
    title: "Data Structures and Algorithms Complete Course",
    author: "GeeksforGeeks (GfG)",
    rating: 4.3,
    price: 44.59,
    discountPrice: 12.22,
    img: "assets/5.png",
    about:
      "Data Structures and Algorithms Complete Course mavzusiga oid eng asosiy tushunchalar va amaliyotlarni o\u2018z ichiga oladi.",
    comments: [
      {
        username: "ali_backend",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-14",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-05-06",
        rating: 4,
      },
      {
        username: "jamshid.dev",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-05-04",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-05-17",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-05-02",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-04-05",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-04-04",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-05-14",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-14",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-27",
        rating: 5,
      },
    ],
  },
  {
    id: 6,
    title: "100 Days of Code: The Complete Python Pro",
    author: "Dr. Angela Yu",
    rating: 4.7,
    price: 86.69,
    discountPrice: 15.47,
    img: "assets/6.png",
    about:
      "Bu kurs orqali siz 100 Days of Code bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "webDev90",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-05-01",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-10",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-12",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-03-30",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-04-25",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-04-28",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-11",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-02-21",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-11",
        rating: 4,
      },
      {
        username: "jamshid.dev",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-01",
        rating: 4,
      },
    ],
  },
  {
    id: 7,
    title: "The Complete Full-Stack Web Development Bootcamp",
    author: "Dr. Angela Yu",
    rating: 4.7,
    price: 78.17,
    discountPrice: 12.16,
    img: "assets/7.png",
    about:
      "Agar siz The Complete Full-Stack Web Development Bootcamp'ni mukammal o\u2018rganmoqchi bo\u2018lsangiz, ushbu kurs aynan siz uchun. Bosqichma-bosqich tushuntirilgan.",
    comments: [
      {
        username: "simpleUser",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-27",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-18",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-10",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-07",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-04-06",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-04",
        rating: 5,
      },
      {
        username: "nodyCoder",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-05",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-05-03",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-17",
        rating: 5,
      },
      {
        username: "nodyCoder",
        comment: "Narxiga yarasha sifat.",
        date: "2025-05-06",
        rating: 4,
      },
    ],
  },
  {
    id: 8,
    title: "[NEW] Ultimate AWS Certified Cloud Practitioner CLF-C02",
    author: "Stephane Maarek",
    rating: 4.8,
    price: 23.24,
    discountPrice: 16.85,
    img: "assets/8.png",
    about:
      "Ushbu kurs sizga [NEW] Ultimate AWS Certified Cloud Practitioner CLF-C02 bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "x_dev",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-23",
        rating: 5,
      },
      {
        username: "coderUz",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-05-15",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Narxiga yarasha sifat.",
        date: "2025-05-05",
        rating: 4,
      },
      {
        username: "bekzodtech",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-11",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-06",
        rating: 5,
      },
      {
        username: "nodyCoder",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-03-04",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-03-21",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-19",
        rating: 5,
      },
      {
        username: "coderQueen",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-07",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-04-04",
        rating: 5,
      },
    ],
  },
  {
    id: 9,
    title: "Ultimate AWS Certified Solutions Architect Associate",
    author: "Stephane Maarek",
    rating: 4.4,
    price: 63.3,
    discountPrice: 10.67,
    img: "assets/9.png",
    about:
      "Bu kurs orqali siz Ultimate AWS Certified Solutions Architect Associate bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "design2code",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-19",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-26",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-02",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-05-08",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-05-20",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-03-01",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-21",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-05-06",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-02-25",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-03-23",
        rating: 4,
      },
    ],
  },
  {
    id: 10,
    title: "The Complete Python Bootcamp From Zero to Hero",
    author: "Jose Portilla",
    rating: 4.4,
    price: 93.85,
    discountPrice: 17.19,
    img: "assets/10.png",
    about:
      "Agar siz The Complete Python Bootcamp From Zero to Hero'ni mukammal o\u2018rganmoqchi bo\u2018lsangiz, ushbu kurs aynan siz uchun. Bosqichma-bosqich tushuntirilgan.",
    comments: [
      {
        username: "jsMaster",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-03-13",
        rating: 5,
      },
      {
        username: "design2code",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-18",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-04-03",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-02-23",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-03-04",
        rating: 5,
      },
      {
        username: "simpleUser",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-30",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-04-21",
        rating: 4,
      },
      {
        username: "shahzoda.js",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-05-05",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-02",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-05-19",
        rating: 4,
      },
    ],
  },
  {
    id: 11,
    title: "Building a Parser from scratch",
    author: "Dmitry Soshnikov",
    rating: 4.7,
    price: 76.35,
    discountPrice: 10.4,
    img: "assets/11.png",
    about:
      "Building a Parser from scratch mavzusiga oid eng asosiy tushunchalar va amaliyotlarni o\u2018z ichiga oladi.",
    comments: [
      {
        username: "nodyCoder",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-04-22",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Narxiga yarasha sifat.",
        date: "2025-05-21",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-02",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-13",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-02",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-03-06",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-05-19",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-03-16",
        rating: 4,
      },
      {
        username: "design2code",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-25",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-20",
        rating: 4,
      },
    ],
  },
  {
    id: 12,
    title: "11 Essential Coding Interview Questions + Coding Exercises!",
    author: "Y K",
    rating: 4.5,
    price: 35.29,
    discountPrice: 12.54,
    img: "assets/12.png",
    about:
      "11 Essential Coding Interview Questions + Coding Exercises! mavzusiga oid eng asosiy tushunchalar va amaliyotlarni o\u2018z ichiga oladi.",
    comments: [
      {
        username: "jsMaster",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-05-19",
        rating: 4,
      },
      {
        username: "bekzodtech",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-19",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-05-13",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-14",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-28",
        rating: 4,
      },
      {
        username: "shahzoda.js",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-07",
        rating: 5,
      },
      {
        username: "nodyCoder",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-29",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-04-15",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-25",
        rating: 5,
      },
      {
        username: "nodyCoder",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-01",
        rating: 4,
      },
    ],
  },
  {
    id: 13,
    title: "Data Structures : Binary Tree Animations and...",
    author: "Dinesh Varyani",
    rating: 4.3,
    price: 73.05,
    discountPrice: 17.97,
    img: "assets/13.png",
    about:
      "Agar siz Data Structures 'ni mukammal o\u2018rganmoqchi bo\u2018lsangiz, ushbu kurs aynan siz uchun. Bosqichma-bosqich tushuntirilgan.",
    comments: [
      {
        username: "coderQueen",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-22",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-22",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-05-06",
        rating: 4,
      },
      {
        username: "bekzodtech",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-25",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-05-05",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-28",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-02-25",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-03-06",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-04",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-02",
        rating: 4,
      },
    ],
  },
  {
    id: 14,
    title: "Windows Programming using Visual C++ and MFC",
    author: "Haris Kilikotu",
    rating: 4.7,
    price: 76.79,
    discountPrice: 10.96,
    img: "assets/14.png",
    about:
      "Windows Programming using Visual C++ and MFC mavzusiga oid eng asosiy tushunchalar va amaliyotlarni o\u2018z ichiga oladi.",
    comments: [
      {
        username: "bekzodtech",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-05-20",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-02-26",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-03-24",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-05-02",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-02",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-05-04",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-25",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-02",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-19",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-15",
        rating: 5,
      },
    ],
  },
  {
    id: 15,
    title: "Big O Notation for Algorithms in plain English",
    author: "James Cutajar",
    rating: 4.6,
    price: 20.18,
    discountPrice: 13.01,
    img: "assets/15.png",
    about:
      "Agar siz Big O Notation for Algorithms in plain English'ni mukammal o\u2018rganmoqchi bo\u2018lsangiz, ushbu kurs aynan siz uchun. Bosqichma-bosqich tushuntirilgan.",
    comments: [
      {
        username: "webDev90",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-06",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-01",
        rating: 4,
      },
      {
        username: "shahzoda.js",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-30",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-02-22",
        rating: 4,
      },
      {
        username: "shahzoda.js",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-12",
        rating: 4,
      },
      {
        username: "jamshid.dev",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-02-28",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-16",
        rating: 4,
      },
      {
        username: "jamshid.dev",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-06",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-04-19",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-01",
        rating: 5,
      },
    ],
  },
  {
    id: 16,
    title: "Java Tutorial for Complete Beginners",
    author: "John Purcell",
    rating: 4.6,
    price: 55.95,
    discountPrice: 12.29,
    img: "assets/16.png",
    about:
      "Bu kurs orqali siz Java Tutorial for Complete Beginners bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "simpleUser",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-15",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Narxiga yarasha sifat.",
        date: "2025-05-17",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-03-19",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-04-15",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-02-23",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-03-25",
        rating: 4,
      },
      {
        username: "bekzodtech",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-03",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-17",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-05-12",
        rating: 5,
      },
      {
        username: "simpleUser",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-28",
        rating: 4,
      },
    ],
  },
  {
    id: 17,
    title: "Automate the Boring Stuff with Python Programming",
    author: "Al Sweigart",
    rating: 4.4,
    price: 82.14,
    discountPrice: 16.77,
    img: "assets/17.png",
    about:
      "Automate the Boring Stuff with Python Programming mavzusiga oid eng asosiy tushunchalar va amaliyotlarni o\u2018z ichiga oladi.",
    comments: [
      {
        username: "simpleUser",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-02-22",
        rating: 5,
      },
      {
        username: "simpleUser",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-04",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-03",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-05-17",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-06",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-04-07",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-02-26",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-25",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-08",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-01",
        rating: 5,
      },
    ],
  },
  {
    id: 18,
    title: "Machine Learning A-Z: AI, Python & R + ChatGPT Prize",
    author: "Kirill Eremenko, Hadelin de Ponteves...",
    rating: 4.3,
    price: 24.73,
    discountPrice: 17.03,
    img: "assets/18.png",
    about:
      "Agar siz Machine Learning A-Z'ni mukammal o\u2018rganmoqchi bo\u2018lsangiz, ushbu kurs aynan siz uchun. Bosqichma-bosqich tushuntirilgan.",
    comments: [
      {
        username: "design2code",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-02",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-10",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-16",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-16",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-04-28",
        rating: 5,
      },
      {
        username: "nodyCoder",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-07",
        rating: 4,
      },
      {
        username: "javohirx",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-02-28",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-23",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-14",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-23",
        rating: 5,
      },
    ],
  },
  {
    id: 19,
    title: "The Web Developer Bootcamp 2025",
    author: "Colt Steele",
    rating: 4.6,
    price: 35.09,
    discountPrice: 16.59,
    img: "assets/19.png",
    about:
      "Bu kurs orqali siz The Web Developer Bootcamp 2025 bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "jsMaster",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-04-23",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-04-25",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-05-03",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-19",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-05-12",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-03-06",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-05-07",
        rating: 5,
      },
      {
        username: "nodyCoder",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-08",
        rating: 5,
      },
      {
        username: "coderQueen",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-02-24",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-02-28",
        rating: 5,
      },
    ],
  },
  {
    id: 20,
    title: "The Complete JavaScript Course 2025: From Zero to...",
    author: "Jonas Schmedtmann",
    rating: 4.4,
    price: 73.54,
    discountPrice: 16.85,
    img: "assets/20.png",
    about:
      "The Complete JavaScript Course 2025 mavzusiga oid eng asosiy tushunchalar va amaliyotlarni o\u2018z ichiga oladi.",
    comments: [
      {
        username: "bekzodtech",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-16",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-28",
        rating: 4,
      },
      {
        username: "shahzoda.js",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-04-28",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-11",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-26",
        rating: 4,
      },
      {
        username: "bekzodtech",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-29",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-22",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-02-21",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-05-14",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-26",
        rating: 5,
      },
    ],
  },
  {
    id: 21,
    title: "Adobe Photoshop Masterclass with Photoshop 2025 + AI",
    author: "Phil Ebiner",
    rating: 4.4,
    price: 77.57,
    discountPrice: 12.14,
    img: "assets/21.png",
    about:
      "Bu kurs orqali siz Adobe Photoshop Masterclass with Photoshop 2025 + AI bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "design2code",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-09",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-03",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-02",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-17",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-04-29",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-02-24",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-24",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-11",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-20",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-14",
        rating: 5,
      },
    ],
  },
  {
    id: 22,
    title: "The Ultimate Drawing Course - Beginner to Advanced",
    author: "Jaysen Batchelor",
    rating: 4.5,
    price: 94.12,
    discountPrice: 13.98,
    img: "assets/22.png",
    about:
      "Bu kurs orqali siz The Ultimate Drawing Course - Beginner to Advanced bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "x_dev",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-04",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-03",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-04-04",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-05-05",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-12",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-04-02",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-03-18",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-03",
        rating: 4,
      },
      {
        username: "coderUz",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-04-27",
        rating: 4,
      },
      {
        username: "bekzodtech",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-22",
        rating: 5,
      },
    ],
  },
  {
    id: 23,
    title: "After Effects CC Masters: VFX, Motion Graphics, Animation+",
    author: "Phil Ebiner",
    rating: 4.4,
    price: 66.11,
    discountPrice: 14.18,
    img: "assets/23.png",
    about:
      "Ushbu kurs sizga After Effects CC Masters bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "design2code",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-10",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-29",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-05-07",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-02-20",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-05",
        rating: 4,
      },
      {
        username: "jamshid.dev",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-03-14",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-30",
        rating: 4,
      },
      {
        username: "coderUz",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-20",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-05-14",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-10",
        rating: 5,
      },
    ],
  },
  {
    id: 24,
    title: "Complete Blender Creator: Learn 3D Modelling for Beginners",
    author: "Grant Abbitt",
    rating: 4.7,
    price: 54.24,
    discountPrice: 14.32,
    img: "assets/24.png",
    about:
      "Agar siz Complete Blender Creator'ni mukammal o\u2018rganmoqchi bo\u2018lsangiz, ushbu kurs aynan siz uchun. Bosqichma-bosqich tushuntirilgan.",
    comments: [
      {
        username: "coderQueen",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-03-21",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-05-05",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-01",
        rating: 5,
      },
      {
        username: "coderUz",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-03-26",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-26",
        rating: 4,
      },
      {
        username: "jsMaster",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-26",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-04-20",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-11",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-28",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-14",
        rating: 5,
      },
    ],
  },
  {
    id: 25,
    title: "Character Art School: The Complete Character Drawing",
    author: "Scott Harris",
    rating: 4.5,
    price: 62.53,
    discountPrice: 14.25,
    img: "assets/25.png",
    about:
      "Ushbu kurs sizga Character Art School bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "design2code",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-03-19",
        rating: 4,
      },
      {
        username: "coderUz",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-05-18",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-08",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-04-13",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-09",
        rating: 5,
      },
      {
        username: "ali_backend",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-30",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Narxiga yarasha sifat.",
        date: "2025-03-20",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-05-09",
        rating: 5,
      },
      {
        username: "jsMaster",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-03-23",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-13",
        rating: 4,
      },
    ],
  },
  {
    id: 26,
    title: "The Complete SQL Bootcamp: Go from Zero to Hero",
    author: "Jose Portilla",
    rating: 4.2,
    price: 50.49,
    discountPrice: 16.59,
    img: "assets/26.png",
    about:
      "Bu kurs orqali siz The Complete SQL Bootcamp bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "coderUz",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-04-02",
        rating: 4,
      },
      {
        username: "shahzoda.js",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-03",
        rating: 4,
      },
      {
        username: "shahzoda.js",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-02-21",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-07",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-05-14",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-23",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-31",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-30",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-05-02",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-22",
        rating: 5,
      },
    ],
  },
  {
    id: 27,
    title: "An Entire MBA in 1 Course:Award Winning",
    author: "Chris Haroun",
    rating: 4.6,
    price: 58.47,
    discountPrice: 12.21,
    img: "assets/27.png",
    about:
      "Ushbu kurs sizga An Entire MBA in 1 Course bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "javohirx",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-02-26",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-03-06",
        rating: 5,
      },
      {
        username: "coderQueen",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-03-03",
        rating: 5,
      },
      {
        username: "x_dev",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-04-30",
        rating: 5,
      },
      {
        username: "simpleUser",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-05-16",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-04-01",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-05-12",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-03-26",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-26",
        rating: 4,
      },
      {
        username: "simpleUser",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-04-23",
        rating: 5,
      },
    ],
  },
  {
    id: 28,
    title: "Zero to Hero in SQL: SQL for Data Analytics",
    author: "Maven Analytics",
    rating: 4.5,
    price: 76.13,
    discountPrice: 13.12,
    img: "assets/28.png",
    about:
      "Ushbu kurs sizga Zero to Hero in SQL bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "simpleUser",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-10",
        rating: 5,
      },
      {
        username: "webDev90",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-03-12",
        rating: 5,
      },
      {
        username: "coderQueen",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-03-17",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-03-16",
        rating: 5,
      },
      {
        username: "bekzodtech",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-05-03",
        rating: 4,
      },
      {
        username: "webDev90",
        comment:
          "Ba\u2019zi joylari chalkash bo\u2018ldi, lekin umumiy olganda ajoyib.",
        date: "2025-02-24",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-04-06",
        rating: 4,
      },
      {
        username: "ali_backend",
        comment: "Tavsiya qilaman, ayniqsa yangi boshlovchilarga.",
        date: "2025-05-12",
        rating: 4,
      },
      {
        username: "jamshid.dev",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-03-25",
        rating: 4,
      },
      {
        username: "webDev90",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-22",
        rating: 5,
      },
    ],
  },
  {
    id: 29,
    title: "Microsoft Power BI Desktop for Business Intelligence",
    author: "Maven Analytics",
    rating: 4.8,
    price: 87.61,
    discountPrice: 15.15,
    img: "assets/29.png",
    about:
      "Bu kurs orqali siz Microsoft Power BI Desktop for Business Intelligence bo\u2018yicha nazariy va amaliy bilimga ega bo\u2018lasiz.",
    comments: [
      {
        username: "jsMaster",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-05-03",
        rating: 5,
      },
      {
        username: "jamshid.dev",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-05-12",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-26",
        rating: 5,
      },
      {
        username: "javohirx",
        comment: "Narxiga yarasha sifat.",
        date: "2025-04-26",
        rating: 5,
      },
      {
        username: "coderUz",
        comment: "Narxiga yarasha sifat.",
        date: "2025-02-26",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-05-03",
        rating: 4,
      },
      {
        username: "javohirx",
        comment: "Colt Steele har doimgidek zo\u2018r.",
        date: "2025-02-26",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-04-17",
        rating: 4,
      },
      {
        username: "bekzodtech",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-03-17",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-03-30",
        rating: 4,
      },
    ],
  },
  {
    id: 30,
    title: "PMP Certification Exam Prep Course 35 PDU Contact",
    author: "TIA Education, Andrew Ramdayal",
    rating: 4.7,
    price: 92.99,
    discountPrice: 10.33,
    img: "assets/30.png",
    about:
      "Ushbu kurs sizga PMP Certification Exam Prep Course 35 PDU Contact bo\u2018yicha mukammal bilim beradi. Darslar interaktiv va amaliy misollar bilan boyitilgan.",
    comments: [
      {
        username: "coderQueen",
        comment: "Har bir modul aniq va qisqa.",
        date: "2025-02-23",
        rating: 5,
      },
      {
        username: "shahzoda.js",
        comment: "Eng yaxshi ko\u2018rilgan kurslarimdan biri.",
        date: "2025-03-14",
        rating: 5,
      },
      {
        username: "simpleUser",
        comment: "Algoritm mavzularini yaxshi o'rgatgan.",
        date: "2025-05-09",
        rating: 4,
      },
      {
        username: "coderUz",
        comment: "Ustoz juda tushunarli tushuntirgan.",
        date: "2025-05-03",
        rating: 4,
      },
      {
        username: "coderQueen",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-05-05",
        rating: 5,
      },
      {
        username: "design2code",
        comment: "Boshidan oxirigacha juda foydali bo\u2018ldi.",
        date: "2025-05-12",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Dizayn va tushuntirish uslubi juda yuqori darajada.",
        date: "2025-05-16",
        rating: 4,
      },
      {
        username: "nodyCoder",
        comment: "Topshiriqlar juda foydali.",
        date: "2025-04-05",
        rating: 4,
      },
      {
        username: "design2code",
        comment: "Ko\u2018proq testlar bo\u2018lsa yaxshi bo\u2018lardi.",
        date: "2025-05-07",
        rating: 4,
      },
      {
        username: "x_dev",
        comment: "Yaxshi darslar, lekin ko'proq amaliy misollar kerak.",
        date: "2025-03-30",
        rating: 4,
      },
    ],
  },
];
