[
  {
    "id": 1,
    "name": "Smart Lock X100",
    "price": 12500,
    "old_price": 15000,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 34,
    "rating": 4,
    "img": "assets/Smart_Lock_X100.png",
    "category": "Smart Locks"
  },
  {
    "id": 2,
    "name": "RFID Card Reader Pro",
    "price": 3800,
    "old_price": 4200,
    "currency": "₽",
    "availability": "Нет в наличии",
    "reviews": 12,
    "rating": 3,
    "img": "assets/RFID_Card_Reader_Pro.png",
    "category": "Access Control"
  },
  {
    "id": 3,
    "name": "Biometric Door Lock A5",
    "price": 19800,
    "old_price": 21000,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 28,
    "rating": 5,
    "img": "assets/Biometric_Door_Lock_A5.png",
    "category": "Biometric Locks"
  },
  {
    "id": 4,
    "name": "Touchscreen Keypad Entry",
    "price": 11200,
    "old_price": 13000,
    "currency": "₽",
    "availability": "Нет в наличии",
    "reviews": 8,
    "rating": 2,
    "img": "assets/Touchscreen_Keypad_Entry.png",
    "category": "Keypad Locks"
  },
  {
    "id": 5,
    "name": "Digital Handle Lock Q7",
    "price": 14700,
    "old_price": 16500,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 15,
    "rating": 4,
    "img": "assets/Digital_Handle_Lock_Q7.png",
    "category": "Smart Locks"
  },
  {
    "id": 6,
    "name": "Hotel Lock System Pro",
    "price": 22500,
    "old_price": 24000,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 6,
    "rating": 5,
    "img": "assets/Hotel_Lock_System_Pro.png",
    "category": "Hotel Locks"
  },
  {
    "id": 7,
    "name": "Wireless Entry Lock Z9",
    "price": 8700,
    "old_price": 9500,
    "currency": "₽",
    "availability": "Нет в наличии",
    "reviews": 21,
    "rating": 3,
    "img": "assets/Wireless_Entry_Lock_Z9.png",
    "category": "Wireless Locks"
  },
  {
    "id": 8,
    "name": "Fingerprint Reader Secure",
    "price": 5600,
    "old_price": 6200,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 19,
    "rating": 4,
    "img": "assets/Fingerprint_Reader_Secure.png",
    "category": "Biometric Readers"
  },
  {
    "id": 9,
    "name": "Smart Doorbell with Lock",
    "price": 13900,
    "old_price": 16000,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 11,
    "rating": 3,
    "img": "assets/Smart_Doorbell_with_Lock.png",
    "category": "Smart Home"
  },
  {
    "id": 10,
    "name": "Remote Control Lock R4",
    "price": 7200,
    "old_price": 8000,
    "currency": "₽",
    "availability": "Нет в наличии",
    "reviews": 5,
    "rating": 2,
    "img": "assets/Remote_Control_Lock_R4.png",
    "category": "Remote Locks"
  },
  {
    "id": 11,
    "name": "Keyless Entry Smart Lock",
    "price": 17600,
    "old_price": 19000,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 22,
    "rating": 4,
    "img": "assets/Keyless_Entry_Smart_Lock.png",
    "category": "Smart Locks"
  },
  {
    "id": 12,
    "name": "Access Panel with RFID",
    "price": 6600,
    "old_price": 7200,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 9,
    "rating": 3,
    "img": "assets/Access_Panel_with_RFID.png",
    "category": "Access Control"
  },
  {
    "id": 13,
    "name": "Hotel Room Access Kit",
    "price": 15300,
    "old_price": 17000,
    "currency": "₽",
    "availability": "Нет в наличии",
    "reviews": 7,
    "rating": 2,
    "img": "assets/Hotel_Room_Access_Kit.png",
    "category": "Hotel Locks"
  },
  {
    "id": 14,
    "name": "Premium Lock Cylinder",
    "price": 4700,
    "old_price": 5000,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 4,
    "rating": 1,
    "img": "assets/Premium_Lock_Cylinder.png",
    "category": "Cylinders"
  },
  {
    "id": 15,
    "name": "Bluetooth Entry Lock B2",
    "price": 10100,
    "old_price": 11500,
    "currency": "₽",
    "availability": "В наличии",
    "reviews": 18,
    "rating": 4,
    "img": "assets/Bluetooth_Entry_Lock_B2.png",
    "category": "Wireless Locks"
  }
]
